name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    environment: default
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        run: xcodebuild -scheme blackberry-dynamics-ios-sdk-Package -destination generic/platform=iOS
